export const getDiffViewerTheme = (isDarkMode: boolean) => ({
  variables: {
    dark: {
      diffViewerBackground: isDarkMode ? '#09090b' : '#ffffff',
      gutterBackground: isDarkMode ? '#18181b' : '#f4f4f5',
      addedBackground: isDarkMode ? '#14532d' : '#dcfce7',
      addedColor: isDarkMode ? '#bbf7d0' : '#166534',
      removedBackground: isDarkMode ? '#7f1d1d' : '#fee2e2',
      removedColor: isDarkMode ? '#fca5a5' : '#991b1b',
      wordAddedBackground: isDarkMode ? '#15803d' : '#86efac',
      wordRemovedBackground: isDarkMode ? '#b91c1c' : '#fca5a5',
      addedGutterBackground: isDarkMode ? '#166534' : '#bbf7d0',
      removedGutterBackground: isDarkMode ? '#991b1b' : '#fca5a5',
      gutterColor: isDarkMode ? '#71717a' : '#52525b',
      highlightBackground: isDarkMode ? '#27272a' : '#f4f4f5',
      highlightGutterBackground: isDarkMode ? '#3f3f46' : '#e4e4e7',
    },
    light: {
      diffViewerBackground: '#ffffff',
      gutterBackground: '#f4f4f5',
      addedBackground: '#dcfce7',
      addedColor: '#166534',
      removedBackground: '#fee2e2',
      removedColor: '#991b1b',
      wordAddedBackground: '#86efac',
      wordRemovedBackground: '#fca5a5',
      addedGutterBackground: '#bbf7d0',
      removedGutterBackground: '#fca5a5',
      gutterColor: '#52525b',
      highlightBackground: '#f4f4f5',
      highlightGutterBackground: '#e4e4e7',
    },
  },
});
